"""
Weekly operational report generator.

Aggregates tasks, tickets, documents, and AI activity from the past week,
then produces a narrative report via LLM or template fallback.
"""

import logging
import time
from datetime import timedelta

from django.utils import timezone
from django.db.models import Count

from ai.services.llm import generate_completion, get_model_name
from ai.services.interaction_logger import log_interaction

logger = logging.getLogger('ai')


def _gather_week_stats(week_start, week_end) -> dict:
    """Collect operational metrics for the report date range."""
    from tasks.models import Task
    from tickets.models import Ticket
    from documents.models import Document
    from ai.models import AIInteractionLog

    tasks = Task.objects.filter(created_at__date__gte=week_start, created_at__date__lte=week_end)
    tickets = Ticket.objects.filter(created_at__date__gte=week_start, created_at__date__lte=week_end)
    docs = Document.objects.filter(created_at__date__gte=week_start, created_at__date__lte=week_end)
    ai_logs = AIInteractionLog.objects.filter(
        created_at__date__gte=week_start, created_at__date__lte=week_end
    )

    task_by_status = dict(tasks.values('status').annotate(c=Count('id')).values_list('status', 'c'))
    ticket_by_status = dict(tickets.values('status').annotate(c=Count('id')).values_list('status', 'c'))

    return {
        'tasks_created': tasks.count(),
        'tasks_completed': tasks.filter(status='DONE').count(),
        'tasks_by_status': task_by_status,
        'tickets_created': tickets.count(),
        'tickets_resolved': tickets.filter(status='RESOLVED').count(),
        'tickets_by_status': ticket_by_status,
        'documents_uploaded': docs.count(),
        'ai_interactions': ai_logs.count(),
        'ai_by_type': dict(ai_logs.values('interaction_type').annotate(c=Count('id')).values_list('interaction_type', 'c')),
    }


def _template_report(stats: dict, week_start, week_end) -> str:
    """Offline report template when no LLM is configured."""
    lines = [
        f'# Weekly Operations Report',
        f'**Period:** {week_start} to {week_end}',
        '',
        '## Task Summary',
        f"- Tasks created: **{stats['tasks_created']}**",
        f"- Tasks completed: **{stats['tasks_completed']}**",
        f"- Status breakdown: {stats['tasks_by_status']}",
        '',
        '## Support Tickets',
        f"- Tickets opened: **{stats['tickets_created']}**",
        f"- Tickets resolved: **{stats['tickets_resolved']}**",
        f"- Status breakdown: {stats['tickets_by_status']}",
        '',
        '## Documents & AI',
        f"- Documents uploaded: **{stats['documents_uploaded']}**",
        f"- AI interactions: **{stats['ai_interactions']}**",
        f"- AI activity by type: {stats['ai_by_type']}",
        '',
        '## Recommendations',
        '- Review open high-priority tickets',
        '- Ensure document knowledge base stays indexed for RAG chat',
        '- Monitor Celery workers for background processing health',
        '',
        '*(Generated by local template — set OPENAI_API_KEY for GPT narrative reports.)*',
    ]
    return '\n'.join(lines)


def generate_weekly_report(user, week_start=None, week_end=None) -> dict:
    """
    Build a weekly report for the given date range (defaults to last 7 days).

    Returns dict with title, content, stats, model_used.
    """
    start = time.time()
    today = timezone.now().date()
    if not week_end:
        week_end = today
    if not week_start:
        week_start = today - timedelta(days=7)

    stats = _gather_week_stats(week_start, week_end)
    title = f'Weekly Report {week_start} — {week_end}'

    import os
    if os.getenv('OPENAI_API_KEY'):
        system = 'You are an operations analyst. Write a professional weekly report in Markdown.'
        user_prompt = f'Generate a weekly ops report from this data:\n{stats}'
        content, tokens = generate_completion(system, user_prompt, max_tokens=1000)
        model = get_model_name()
    else:
        content = _template_report(stats, week_start, week_end)
        tokens = len(content.split())
        model = 'local-template'

    duration_ms = int((time.time() - start) * 1000)

    log_interaction(
        user=user,
        interaction_type='GENERATE_REPORT',
        input_data={'week_start': str(week_start), 'week_end': str(week_end)},
        output_data={'title': title, 'stats': stats},
        model_used=model,
        tokens_used=tokens,
        duration_ms=duration_ms,
    )

    return {
        'title': title,
        'content': content,
        'week_start': week_start,
        'week_end': week_end,
        'stats': stats,
        'model_used': model,
        'duration_ms': duration_ms,
    }
