# Generated by Django 5.1.15 on 2026-07-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ai_category',
            field=models.CharField(blank=True, help_text='AI-predicted category.', max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ai_confidence',
            field=models.FloatField(default=0.0, help_text='Classification confidence 0-1.'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ai_department',
            field=models.CharField(blank=True, help_text='AI-suggested department.', max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ai_priority',
            field=models.CharField(blank=True, help_text='AI-suggested priority.', max_length=20),
        ),
    ]
