# Generated by Django 6.0.7 on 2026-08-04 07:25

import candidates.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('highest_qualification', models.CharField(max_length=100)),
                ('university', models.CharField(blank=True, max_length=200)),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('experience_years', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('current_company', models.CharField(blank=True, max_length=150)),
                ('current_job_title', models.CharField(blank=True, max_length=150)),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('preferred_department', models.CharField(blank=True, max_length=100)),
                ('preferred_job_role', models.CharField(blank=True, max_length=150)),
                ('technical_skills', models.TextField(blank=True, help_text='Comma-separated skills')),
                ('soft_skills', models.TextField(blank=True, help_text='Comma-separated skills')),
                ('programming_languages', models.TextField(blank=True, help_text='Comma-separated languages')),
                ('certifications', models.TextField(blank=True)),
                ('projects', models.TextField(blank=True)),
                ('communication_score', models.PositiveSmallIntegerField(default=0, help_text='0-100')),
                ('interview_score', models.PositiveSmallIntegerField(default=0, help_text='0-100')),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to=candidates.models.resume_upload_path)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='candidate_photos/')),
                ('application_date', models.DateField(auto_now_add=True)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('RESUME_SHORTLISTED', 'Resume Shortlisted'), ('ASSESSMENT_PENDING', 'Assessment Pending'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('INTERVIEW_COMPLETED', 'Interview Completed'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected'), ('HIRED', 'Hired')], default='APPLIED', max_length=30)),
                ('last_prediction', models.CharField(blank=True, max_length=20)),
                ('last_prediction_probability', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
